//! Opcodes

use std::fmt;

#[repr(u8)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Opcode {
    // Row 0x0_
    BrkImp = 0x00,
    OraInx = 0x01,
    OraZpg = 0x05,
    AslZpg = 0x06,
    PhpImp = 0x08,
    OraImm = 0x09,
    AslImp = 0x0a,
    OraAbs = 0x0d,
    AslAbs = 0x0e,
    
    // Row 0x1_
    BplRel = 0x10,
    OraIny = 0x11,
    OraZpx = 0x15,
    AslZpx = 0x16,
    ClcImp = 0x18,
    OraAby = 0x19,
    OraAbx = 0x1d,
    AslAbx = 0x1e,
    
    // Row 0x2_
    JsrAbs = 0x20,
    AndInx = 0x21,
    BitZpg = 0x24,
    AndZpg = 0x25,
    RolZpg = 0x26,
    PlpImp = 0x28,
    AndImm = 0x29,
    RolImp = 0x2a,
    BitAbs = 0x2c,
    AndAbs = 0x2d,
    RolAbs = 0x2e,
    
    // Row 0x3_
    BmiRel = 0x30,
    AndIny = 0x31,
    AndZpx = 0x35,
    RolZpx = 0x36,
    SecImp = 0x38,
    AndAby = 0x39,
    AndAbx = 0x3d,
    RolAbx = 0x3e,
    
    // Row 0x4_
    RtiImp = 0x40,
    EorInx = 0x41,
    EorZpg = 0x45,
    LsrZpg = 0x46,
    PhaImp = 0x48,
    EorImm = 0x49,
    LsrImp = 0x4a,
    JmpAbs = 0x4c,
    EorAbs = 0x4d,
    LsrAbs = 0x4e,
    
    // Row 0x5_
    BvcRel = 0x50,
    EorIny = 0x51,
    EorZpx = 0x55,
    LsrZpx = 0x56,
    CliImp = 0x58,
    EorAby = 0x59,
    EorAbx = 0x5d,
    LsrAbx = 0x5e,
    
    // Row 0x6_
    RtsImp = 0x60,
    AdcInx = 0x61,
    AdcZpg = 0x65,
    RorZpg = 0x66,
    PlaImp = 0x68,
    AdcImm = 0x69,
    RorImp = 0x6a,
    JmpInd = 0x6c,
    AdcAbs = 0x6d,
    RorAbs = 0x6e,
    
    // Row 0x7_
    BvsRel = 0x70,
    AdcIny = 0x71,
    AdcZpx = 0x75,
    RorZpx = 0x76,
    SeiImp = 0x78,
    AdcAby = 0x79,
    AdcAbx = 0x7d,
    RorAbx = 0x7e,
    
    // Row 0x8_
    StaInx = 0x81,
    StyZpg = 0x84,
    StaZpg = 0x85,
    StxZpg = 0x86,
    DeyImp = 0x88,
    TxaImp = 0x8a,
    StyAbs = 0x8c,
    StaAbs = 0x8d,
    StxAbs = 0x8e,
    
    // Row 0x9_
    BccRel = 0x90,
    StaIny = 0x91,
    StyZpx = 0x94,
    StaZpx = 0x95,
    StxZpy = 0x96,
    TyaImp = 0x98,
    StaAby = 0x99,
    TxsImp = 0x9a,
    StaAbx = 0x9d,
    
    // Row 0xa_
    LdyImm = 0xa0,
    LdaInx = 0xa1,
    LdxImm = 0xa2,
    LdyZpg = 0xa4,
    LdaZpg = 0xa5,
    LdxZpg = 0xa6,
    TayImp = 0xa8,
    LdaImm = 0xa9,
    TaxImp = 0xaa,
    LdyAbs = 0xac,
    LdaAbs = 0xad,
    LdxAbs = 0xae,
    
    // Row 0xb_
    BcsRel = 0xb0,
    LdaIny = 0xb1,
    LdyZpx = 0xb4,
    LdaZpx = 0xb5,
    LdxZpy = 0xb6,
    ClvImp = 0xb8,
    LdaAby = 0xb9,
    TsxImp = 0xba,
    LdyAbx = 0xbc,
    LdaAbx = 0xbd,
    LdxAby = 0xbe,
    
    // Row 0xc_
    CpyImm = 0xc0,
    CmpInx = 0xc1,
    CpyZpg = 0xc4,
    CmpZpg = 0xc5,
    DecZpg = 0xc6,
    InyImp = 0xc8,
    CmpImm = 0xc9,
    DexImp = 0xca,
    CpyAbs = 0xcc,
    CmpAbs = 0xcd,
    DecAbs = 0xce,
    
    // Row 0xd_
    BneRel = 0xd0,
    CmpIny = 0xd1,
    CmpZpx = 0xd5,
    DecZpx = 0xd6,
    CldImp = 0xd8,
    CmpAby = 0xd9,
    CmpAbx = 0xdd,
    DecAbx = 0xde,
    
    // Row 0xe_
    CpxImm = 0xe0,
    SbcInx = 0xe1,
    CpxZpg = 0xe4,
    SbcZpg = 0xe5,
    IncZpg = 0xe6,
    InxImp = 0xe8,
    SbcImm = 0xe9,
    NopImp = 0xea,
    CpxAbs = 0xec,
    SbcAbs = 0xed,
    IncAbs = 0xee,
    
    // Row 0xf_
    BeqRel = 0xf0,
    SbcIny = 0xf1,
    SbcZpx = 0xf5,
    IncZpx = 0xf6,
    SedImp = 0xf8,
    SbcAby = 0xf9,
    SbcAbx = 0xfd,
    IncAbx = 0xfe,
    
    // Unsupported opcodes can be handled separately
    Unsupported = 0xff, // Placeholder for unsupported opcodes
}

impl Opcode {
    /// Convert a byte to an Opcode, returning Unsupported for invalid opcodes
    pub fn from_byte(byte: u8) -> Self {
        match byte {
            0x00 => Self::BrkImp,
            0x01 => Self::OraInx,
            0x05 => Self::OraZpg,
            0x06 => Self::AslZpg,
            0x08 => Self::PhpImp,
            0x09 => Self::OraImm,
            0x0a => Self::AslImp,
            0x0d => Self::OraAbs,
            0x0e => Self::AslAbs,
            0x10 => Self::BplRel,
            0x11 => Self::OraIny,
            0x15 => Self::OraZpx,
            0x16 => Self::AslZpx,
            0x18 => Self::ClcImp,
            0x19 => Self::OraAby,
            0x1d => Self::OraAbx,
            0x1e => Self::AslAbx,
            0x20 => Self::JsrAbs,
            0x21 => Self::AndInx,
            0x24 => Self::BitZpg,
            0x25 => Self::AndZpg,
            0x26 => Self::RolZpg,
            0x28 => Self::PlpImp,
            0x29 => Self::AndImm,
            0x2a => Self::RolImp,
            0x2c => Self::BitAbs,
            0x2d => Self::AndAbs,
            0x2e => Self::RolAbs,
            0x30 => Self::BmiRel,
            0x31 => Self::AndIny,
            0x35 => Self::AndZpx,
            0x36 => Self::RolZpx,
            0x38 => Self::SecImp,
            0x39 => Self::AndAby,
            0x3d => Self::AndAbx,
            0x3e => Self::RolAbx,
            0x40 => Self::RtiImp,
            0x41 => Self::EorInx,
            0x45 => Self::EorZpg,
            0x46 => Self::LsrZpg,
            0x48 => Self::PhaImp,
            0x49 => Self::EorImm,
            0x4a => Self::LsrImp,
            0x4c => Self::JmpAbs,
            0x4d => Self::EorAbs,
            0x4e => Self::LsrAbs,
            0x50 => Self::BvcRel,
            0x51 => Self::EorIny,
            0x55 => Self::EorZpx,
            0x56 => Self::LsrZpx,
            0x58 => Self::CliImp,
            0x59 => Self::EorAby,
            0x5d => Self::EorAbx,
            0x5e => Self::LsrAbx,
            0x60 => Self::RtsImp,
            0x61 => Self::AdcInx,
            0x65 => Self::AdcZpg,
            0x66 => Self::RorZpg,
            0x68 => Self::PlaImp,
            0x69 => Self::AdcImm,
            0x6a => Self::RorImp,
            0x6c => Self::JmpInd,
            0x6d => Self::AdcAbs,
            0x6e => Self::RorAbs,
            0x70 => Self::BvsRel,
            0x71 => Self::AdcIny,
            0x75 => Self::AdcZpx,
            0x76 => Self::RorZpx,
            0x78 => Self::SeiImp,
            0x79 => Self::AdcAby,
            0x7d => Self::AdcAbx,
            0x7e => Self::RorAbx,
            0x81 => Self::StaInx,
            0x84 => Self::StyZpg,
            0x85 => Self::StaZpg,
            0x86 => Self::StxZpg,
            0x88 => Self::DeyImp,
            0x8a => Self::TxaImp,
            0x8c => Self::StyAbs,
            0x8d => Self::StaAbs,
            0x8e => Self::StxAbs,
            0x90 => Self::BccRel,
            0x91 => Self::StaIny,
            0x94 => Self::StyZpx,
            0x95 => Self::StaZpx,
            0x96 => Self::StxZpy,
            0x98 => Self::TyaImp,
            0x99 => Self::StaAby,
            0x9a => Self::TxsImp,
            0x9d => Self::StaAbx,
            0xa0 => Self::LdyImm,
            0xa1 => Self::LdaInx,
            0xa2 => Self::LdxImm,
            0xa4 => Self::LdyZpg,
            0xa5 => Self::LdaZpg,
            0xa6 => Self::LdxZpg,
            0xa8 => Self::TayImp,
            0xa9 => Self::LdaImm,
            0xaa => Self::TaxImp,
            0xac => Self::LdyAbs,
            0xad => Self::LdaAbs,
            0xae => Self::LdxAbs,
            0xb0 => Self::BcsRel,
            0xb1 => Self::LdaIny,
            0xb4 => Self::LdyZpx,
            0xb5 => Self::LdaZpx,
            0xb6 => Self::LdxZpy,
            0xb8 => Self::ClvImp,
            0xb9 => Self::LdaAby,
            0xba => Self::TsxImp,
            0xbc => Self::LdyAbx,
            0xbd => Self::LdaAbx,
            0xbe => Self::LdxAby,
            0xc0 => Self::CpyImm,
            0xc1 => Self::CmpInx,
            0xc4 => Self::CpyZpg,
            0xc5 => Self::CmpZpg,
            0xc6 => Self::DecZpg,
            0xc8 => Self::InyImp,
            0xc9 => Self::CmpImm,
            0xca => Self::DexImp,
            0xcc => Self::CpyAbs,
            0xcd => Self::CmpAbs,
            0xce => Self::DecAbs,
            0xd0 => Self::BneRel,
            0xd1 => Self::CmpIny,
            0xd5 => Self::CmpZpx,
            0xd6 => Self::DecZpx,
            0xd8 => Self::CldImp,
            0xd9 => Self::CmpAby,
            0xdd => Self::CmpAbx,
            0xde => Self::DecAbx,
            0xe0 => Self::CpxImm,
            0xe1 => Self::SbcInx,
            0xe4 => Self::CpxZpg,
            0xe5 => Self::SbcZpg,
            0xe6 => Self::IncZpg,
            0xe8 => Self::InxImp,
            0xe9 => Self::SbcImm,
            0xea => Self::NopImp,
            0xec => Self::CpxAbs,
            0xed => Self::SbcAbs,
            0xee => Self::IncAbs,
            0xf0 => Self::BeqRel,
            0xf1 => Self::SbcIny,
            0xf5 => Self::SbcZpx,
            0xf6 => Self::IncZpx,
            0xf8 => Self::SedImp,
            0xf9 => Self::SbcAby,
            0xfd => Self::SbcAbx,
            0xfe => Self::IncAbx,
            _ => Self::Unsupported,
        }
    }
}

impl fmt::Display for Opcode {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        let name = match self {
            Self::BrkImp => "BRK_IMP",
            Self::OraInx => "ORA_INX",
            Self::OraZpg => "ORA_ZPG",
            Self::AslZpg => "ASL_ZPG",
            Self::PhpImp => "PHP_IMP",
            Self::OraImm => "ORA_IMM",
            Self::AslImp => "ASL_IMP",
            Self::OraAbs => "ORA_ABS",
            Self::AslAbs => "ASL_ABS",
            Self::BplRel => "BPL_REL",
            Self::OraIny => "ORA_INY",
            Self::OraZpx => "ORA_ZPX",
            Self::AslZpx => "ASL_ZPX",
            Self::ClcImp => "CLC_IMP",
            Self::OraAby => "ORA_ABY",
            Self::OraAbx => "ORA_ABX",
            Self::AslAbx => "ASL_ABX",
            Self::JsrAbs => "JSR_ABS",
            Self::AndInx => "AND_INX",
            Self::BitZpg => "BIT_ZPG",
            Self::AndZpg => "AND_ZPG",
            Self::RolZpg => "ROL_ZPG",
            Self::PlpImp => "PLP_IMP",
            Self::AndImm => "AND_IMM",
            Self::RolImp => "ROL_IMP",
            Self::BitAbs => "BIT_ABS",
            Self::AndAbs => "AND_ABS",
            Self::RolAbs => "ROL_ABS",
            Self::BmiRel => "BMI_REL",
            Self::AndIny => "AND_INY",
            Self::AndZpx => "AND_ZPX",
            Self::RolZpx => "ROL_ZPX",
            Self::SecImp => "SEC_IMP",
            Self::AndAby => "AND_ABY",
            Self::AndAbx => "AND_ABX",
            Self::RolAbx => "ROL_ABX",
            Self::RtiImp => "RTI_IMP",
            Self::EorInx => "EOR_INX",
            Self::EorZpg => "EOR_ZPG",
            Self::LsrZpg => "LSR_ZPG",
            Self::PhaImp => "PHA_IMP",
            Self::EorImm => "EOR_IMM",
            Self::LsrImp => "LSR_IMP",
            Self::JmpAbs => "JMP_ABS",
            Self::EorAbs => "EOR_ABS",
            Self::LsrAbs => "LSR_ABS",
            Self::BvcRel => "BVC_REL",
            Self::EorIny => "EOR_INY",
            Self::EorZpx => "EOR_ZPX",
            Self::LsrZpx => "LSR_ZPX",
            Self::CliImp => "CLI_IMP",
            Self::EorAby => "EOR_ABY",
            Self::EorAbx => "EOR_ABX",
            Self::LsrAbx => "LSR_ABX",
            Self::RtsImp => "RTS_IMP",
            Self::AdcInx => "ADC_INX",
            Self::AdcZpg => "ADC_ZPG",
            Self::RorZpg => "ROR_ZPG",
            Self::PlaImp => "PLA_IMP",
            Self::AdcImm => "ADC_IMM",
            Self::RorImp => "ROR_IMP",
            Self::JmpInd => "JMP_IND",
            Self::AdcAbs => "ADC_ABS",
            Self::RorAbs => "ROR_ABS",
            Self::BvsRel => "BVS_REL",
            Self::AdcIny => "ADC_INY",
            Self::AdcZpx => "ADC_ZPX",
            Self::RorZpx => "ROR_ZPX",
            Self::SeiImp => "SEI_IMP",
            Self::AdcAby => "ADC_ABY",
            Self::AdcAbx => "ADC_ABX",
            Self::RorAbx => "ROR_ABX",
            Self::StaInx => "STA_INX",
            Self::StyZpg => "STY_ZPG",
            Self::StaZpg => "STA_ZPG",
            Self::StxZpg => "STX_ZPG",
            Self::DeyImp => "DEY_IMP",
            Self::TxaImp => "TXA_IMP",
            Self::StyAbs => "STY_ABS",
            Self::StaAbs => "STA_ABS",
            Self::StxAbs => "STX_ABS",
            Self::BccRel => "BCC_REL",
            Self::StaIny => "STA_INY",
            Self::StyZpx => "STY_ZPX",
            Self::StaZpx => "STA_ZPX",
            Self::StxZpy => "STX_ZPY",
            Self::TyaImp => "TYA_IMP",
            Self::StaAby => "STA_ABY",
            Self::TxsImp => "TXS_IMP",
            Self::StaAbx => "STA_ABX",
            Self::LdyImm => "LDY_IMM",
            Self::LdaInx => "LDA_INX",
            Self::LdxImm => "LDX_IMM",
            Self::LdyZpg => "LDY_ZPG",
            Self::LdaZpg => "LDA_ZPG",
            Self::LdxZpg => "LDX_ZPG",
            Self::TayImp => "TAY_IMP",
            Self::LdaImm => "LDA_IMM",
            Self::TaxImp => "TAX_IMP",
            Self::LdyAbs => "LDY_ABS",
            Self::LdaAbs => "LDA_ABS",
            Self::LdxAbs => "LDX_ABS",
            Self::BcsRel => "BCS_REL",
            Self::LdaIny => "LDA_INY",
            Self::LdyZpx => "LDY_ZPX",
            Self::LdaZpx => "LDA_ZPX",
            Self::LdxZpy => "LDX_ZPY",
            Self::ClvImp => "CLV_IMP",
            Self::LdaAby => "LDA_ABY",
            Self::TsxImp => "TSX_IMP",
            Self::LdyAbx => "LDY_ABX",
            Self::LdaAbx => "LDA_ABX",
            Self::LdxAby => "LDX_ABY",
            Self::CpyImm => "CPY_IMM",
            Self::CmpInx => "CMP_INX",
            Self::CpyZpg => "CPY_ZPG",
            Self::CmpZpg => "CMP_ZPG",
            Self::DecZpg => "DEC_ZPG",
            Self::InyImp => "INY_IMP",
            Self::CmpImm => "CMP_IMM",
            Self::DexImp => "DEX_IMP",
            Self::CpyAbs => "CPY_ABS",
            Self::CmpAbs => "CMP_ABS",
            Self::DecAbs => "DEC_ABS",
            Self::BneRel => "BNE_REL",
            Self::CmpIny => "CMP_INY",
            Self::CmpZpx => "CMP_ZPX",
            Self::DecZpx => "DEC_ZPX",
            Self::CldImp => "CLD_IMP",
            Self::CmpAby => "CMP_ABY",
            Self::CmpAbx => "CMP_ABX",
            Self::DecAbx => "DEC_ABX",
            Self::CpxImm => "CPX_IMM",
            Self::SbcInx => "SBC_INX",
            Self::CpxZpg => "CPX_ZPG",
            Self::SbcZpg => "SBC_ZPG",
            Self::IncZpg => "INC_ZPG",
            Self::InxImp => "INX_IMP",
            Self::SbcImm => "SBC_IMM",
            Self::NopImp => "NOP_IMP",
            Self::CpxAbs => "CPX_ABS",
            Self::SbcAbs => "SBC_ABS",
            Self::IncAbs => "INC_ABS",
            Self::BeqRel => "BEQ_REL",
            Self::SbcIny => "SBC_INY",
            Self::SbcZpx => "SBC_ZPX",
            Self::IncZpx => "INC_ZPX",
            Self::SedImp => "SED_IMP",
            Self::SbcAby => "SBC_ABY",
            Self::SbcAbx => "SBC_ABX",
            Self::IncAbx => "INC_ABX",
            Self::Unsupported => "UNSUPPO",
        };
        write!(f, "{}", name)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_opcode_from_byte() {
        assert_eq!(Opcode::from_byte(0x00), Opcode::BrkImp);
        assert_eq!(Opcode::from_byte(0x01), Opcode::OraInx);
        assert_eq!(Opcode::from_byte(0xea), Opcode::NopImp);
        assert_eq!(Opcode::from_byte(0xff), Opcode::Unsupported);
        assert_eq!(Opcode::from_byte(0x02), Opcode::Unsupported);
    }

    #[test]
    fn test_opcode_display() {
        assert_eq!(format!("{}", Opcode::BrkImp), "BRK_IMP");
        assert_eq!(format!("{}", Opcode::OraInx), "ORA_INX");
        assert_eq!(format!("{}", Opcode::NopImp), "NOP_IMP");
        assert_eq!(format!("{}", Opcode::Unsupported), "UNSUPPO");
    }

    #[test]
    fn test_opcode_byte_values() {
        assert_eq!(Opcode::BrkImp as u8, 0x00);
        assert_eq!(Opcode::OraInx as u8, 0x01);
        assert_eq!(Opcode::NopImp as u8, 0xea);
    }
}